name: Node CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Install and Build
        run: |
          npm install
          REACT_APP_APPINSIGHTS_KEY="xxx" REACT_APP_K8S_VERSION="1.19.7" REACT_APP_AZ_TEMPLATE_ARG="--template-uri https://raw.githubusercontent.com/khowling/aks-deploy-arm/master/build/main.json" npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
